# Build the module.
steps:

- name: "gcr.io/cloud-builders/go"
  args: ['get', '-d', './...']
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://smartmail/secrets/.env', '.env']

- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy']
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'
  
artifacts:
  objects:
    location: 'gs://smartmail/back-end-go-packages'
    paths: ['main.go']